# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""A2A entrypoint for kagent BYO mode.

Serve with:
    uvicorn app.a2a_app:a2a_app --host 0.0.0.0 --port 8080

Agent card is auto-generated by to_a2a() and exposed at
/.well-known/agent-card.json.
"""

import os

from google.adk.a2a.utils.agent_to_a2a import to_a2a

from app.agent import root_agent

a2a_app = to_a2a(root_agent, port=int(os.getenv("PORT", "8080")))
