apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - agentgateway-ui.yaml
  - agentgateway-llm.yaml
  - agentgateway-mcp.yaml
  - openai-credentials.yaml
  - kagent.yaml
  - a2a-agent.yaml
  - inventory.yaml
  - qdrant.yaml
  - mcp-governance.yaml
