"""Generated tests for time-mcp-server MCP server tools.

This file is automatically generated to test that all tools can be loaded
and executed successfully.
"""

import sys
from pathlib import Path

import pytest

# Add src to Python path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from core.server import DynamicMCPServer  # noqa: E402


class TestToolLoading:
    """Test that all tools can be loaded successfully."""

    def test_server_initialization(self) -> None:
        """Test that the server can be initialized."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        assert server is not None
        assert server.name == "Test Server"

    def test_tool_discovery(self) -> None:
        """Test that tools can be discovered."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")

        # Load tools without failing
        try:
            server.load_tools()
            assert True  # If we get here, loading succeeded
        except RuntimeError:
            pytest.fail("Tool loading failed")

    def test_loaded_tools_count(self) -> None:
        """Test that expected tools are loaded."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()

        # At minimum, we should have the echo tool
        assert len(server.loaded_tools) >= 1
        assert "echo" in server.loaded_tools

    def test_tool_functions_callable(self) -> None:
        """Test that loaded tool functions are callable."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()

        tools = server.get_tools_sync()
        for tool_name, tool in tools.items():
            assert hasattr(tool, 'fn'), f"Tool {tool_name} has no fn attribute"
            assert callable(tool.fn), f"Tool {tool_name} is not callable"


class TestEchoTool:
    """Test the example echo tool."""

    def test_echo_tool_exists(self) -> None:
        """Test that the echo tool exists and can be loaded."""
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()

        assert "echo" in server.loaded_tools

    def test_echo_tool_function(self) -> None:
        """Test that the echo tool function works."""
        # Get the tool from the server
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()

        tools = server.get_tools_sync()
        assert "echo" in tools

        # Call the tool function
        echo_tool = tools["echo"]
        result = echo_tool.fn("Hello, World!")
        assert isinstance(result, str)
        assert "Hello, World!" in result


class TestGetCurrentTimeTool:
    """Tests for the get_current_time tool."""

    def _get_tool(self):
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()
        tools = server.get_tools_sync()
        assert "get_current_time" in tools
        return tools["get_current_time"]

    def test_returns_expected_fields_for_utc(self) -> None:
        tool = self._get_tool()
        result = tool.fn("UTC")

        assert isinstance(result, dict)
        assert result["timezone"] == "UTC"
        for field in ("datetime", "date", "time", "utc_offset", "weekday"):
            assert field in result, f"Missing field: {field}"

    def test_returns_expected_fields_for_named_timezone(self) -> None:
        tool = self._get_tool()
        result = tool.fn("Europe/Bucharest")

        assert result["timezone"] == "Europe/Bucharest"
        assert "T" in result["datetime"]
        assert result["weekday"] in {
            "Monday", "Tuesday", "Wednesday", "Thursday",
            "Friday", "Saturday", "Sunday",
        }
        # Bucharest is UTC+2 in winter (EET) and UTC+3 in summer (EEST)
        assert result["utc_offset"] in {"+0200", "+0300"}

    def test_unknown_timezone_returns_error(self) -> None:
        tool = self._get_tool()
        result = tool.fn("Not/AZone")

        assert result.get("error") == "Unknown timezone"
        assert result.get("timezone") == "Not/AZone"
        assert "hint" in result


class TestConvertTimeTool:
    """Tests for the convert_time tool."""

    def _get_tool(self):
        server = DynamicMCPServer(name="Test Server", tools_dir="src/tools")
        server.load_tools()
        tools = server.get_tools_sync()
        assert "convert_time" in tools
        return tools["convert_time"]

    def test_converts_naive_datetime_between_timezones(self) -> None:
        tool = self._get_tool()
        result = tool.fn(
            datetime_value="2026-01-15T12:00:00",
            source_timezone="UTC",
            target_timezone="Europe/Bucharest",
        )

        assert isinstance(result, dict)
        assert result["source_timezone"] == "UTC"
        assert result["target_timezone"] == "Europe/Bucharest"
        # Bucharest is UTC+2 in January (no DST)
        assert result["converted_datetime"].startswith("2026-01-15T14:00:00")
        assert result["source_utc_offset"] == "+0000"
        assert result["target_utc_offset"] == "+0200"

    def test_converts_across_date_boundary(self) -> None:
        tool = self._get_tool()
        result = tool.fn(
            datetime_value="2026-01-15T23:30:00",
            source_timezone="UTC",
            target_timezone="Asia/Tokyo",
        )

        # Tokyo is UTC+9
        assert result["converted_datetime"].startswith("2026-01-16T08:30:00")
        assert result["target_utc_offset"] == "+0900"

    def test_invalid_source_timezone_returns_error(self) -> None:
        tool = self._get_tool()
        result = tool.fn(
            datetime_value="2026-01-15T12:00:00",
            source_timezone="Not/AZone",
            target_timezone="UTC",
        )

        assert result.get("error") == "Unknown timezone"
        assert "hint" in result

    def test_invalid_datetime_returns_error(self) -> None:
        tool = self._get_tool()
        result = tool.fn(
            datetime_value="not-a-date",
            source_timezone="UTC",
            target_timezone="UTC",
        )

        assert result.get("error") == "Invalid datetime format"
        assert result.get("datetime") == "not-a-date"
        assert "hint" in result

    def test_aware_datetime_input_uses_target_offset(self) -> None:
        tool = self._get_tool()
        result = tool.fn(
            datetime_value="2026-01-15T12:00:00+00:00",
            source_timezone="UTC",
            target_timezone="Europe/Bucharest",
        )

        assert result["converted_datetime"].startswith("2026-01-15T14:00:00")
        assert result["target_utc_offset"] == "+0200"
