apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - agentgateway-ui.yaml
  - agentgateway-llm.yaml
  - agentgateway-mcp.yaml
  - openai-credentials.yaml
  - kagent.yaml
  - agent-sandbox.yaml
  - sandbox-template.yaml
  - phoenix.yaml
  - otel-collector.yaml
  - time-mcp-server.yaml
  - time-agent.yaml
